
services:
  ddap :
    image: 'zouloux/docker-debian-apache-php:v2-php8.3'
    environment:
      # Enable http login password ( default is no password )
      DDAP_LOGIN: 'login'
      DDAP_PASSWORD: 'password'
      # Enabled php devtools in /devtools ( default is no devtools )
      DDAP_DEVTOOLS: 'false'
      DDAP_DEVTOOLS_URL: '/devtools'
      # Custom public path
      DDAP_PUBLIC_PATH: '/var/www/html'
      # Custom PHP config
      DDAP_PHP_DISPLAY_ERRORS: 'false'
      DDAP_PHP_TIMEZONE: 'Europe/Paris'
      DDAP_PHP_MEMORY_LIMIT: '256M'
      DDAP_PHP_MAX_EXECUTION_TIME: '120'
      DDAP_PHP_UPLOAD_SIZE: '128M'
    ports :
      - '8080:80'
    volumes:
      # Map root hidden files
      - './composer.json:/var/www/composer.json'
      - './composer.lock:/var/www/composer.lock'
      - './auth.json:/var/www/auth.json'
      - './vendor:/var/www/vendor'
      - './.env:/var/www/.env'
      # Map public directory
      - './public:/var/www/html'
      # Map dynamic data directory
      - './data:/var/www/data'

